# Generated by Django 3.0.8 on 2020-07-20 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0003_garbage_urgency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbage',
            name='Urgency',
        ),
        migrations.AlterField(
            model_name='garbage',
            name='Capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
